### ISSUE TITLE
Make HTTP endpoints RESTful

### ISSUE THREAD

**Issue by BranislavLazic** [ognjetina/jsonApp#1]
- Remove URL's like /edit_json, /add_json...
- Use PUT for edit
- Use DELETE for deletion
- https://github.com/ognjetina/jsonApp/blob/master/app.py#L77 return 404 status code

**Comment by ognjetina** [comment]
Thanks for the issue, I will implement the changes it makes more sense to set it up RESTful.

**Comment by ognjetina** [comment]
Resolved.
